[project]
name = "llm-prj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "flagembedding>=1.3.5",
    "langchain-core>=1.0.0",
    "langchain-groq>=1.0.0",
    "langdetect>=1.0.9",
    "langgraph>=1.0.0",
    "pymilvus>=2.6.2",
    "pymupdf>=1.26.4",
    "torch>=2.8.0",
    "transformers>=4.56.2",
]