[project]
name = "llm-prj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "docling>=2.54.0",
    "docling-core>=2.48.2",
    "fitz>=0.0.1.dev2",
    "flagembedding>=1.3.5",
    "langchain-core>=0.3.76",
    "langchain-docling>=1.1.0",
    "langchain-groq>=0.3.8",
    "langdetect>=1.0.9",
    "langgraph>=0.6.7",
    "pdfplumber>=0.11.7",
    "pymilvus>=2.6.2",
    "pymupdf>=1.26.4",
    "torch>=2.8.0",
    "transformers>=4.56.2",
]
